[tools]
node = "latest"
bun = "latest"
go = "1.25"
python = "3.11"
uv = "latest"
rust = "stable"
ruby = "latest"
"gem:cocoapods" = "latest"
"npm:@fission-ai/openspec" = "latest"
just = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
