[tools]
node = "latest"
bun = "latest"
go = "1.25"
python = "3.11"
uv = "latest"
rust = "stable"
ruby = "latest"
"gem:cocoapods" = "latest"
"npm:@fission-ai/openspec" = "latest"
just = "latest"
golangci-lint = "v2.12.0"
"npm:@earendil-works/pi-coding-agent" = "latest"
act = "latest"
"pipx:ansible-core" = "latest"
cmake = "latest"
cloud-sql-proxy = "latest"
crane = "latest"
flyctl = "latest"
gh = "latest"
"pipx:git-filter-repo" = "latest"
git-lfs = "latest"
herdr = "latest"
lazygit = "latest"
llmfit = "latest"
mkcert = "latest"
neovim = "latest"
opencode = "latest"
opentofu = "latest"
overmind = "latest"
"pipx:pre-commit" = "latest"
protobuf = "latest"
shellcheck = "latest"
sqlc = "latest"
steampipe = "latest"
trivy = "latest"
tree-sitter = "latest"
zola = "latest"
gomigrate = "latest"
air = "latest"
atlas = "latest"
buf = "latest"
"go:golang.org/x/tools/gopls" = "latest"
grpcurl = "latest"
"go:go.uber.org/nilaway/cmd/nilaway" = "latest"
oapi-codegen = "latest"
protoc-gen-connect-go = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
staticcheck = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"
"go:github.com/google/wire/cmd/wire" = "latest"
"go:go.k6.io/xk6/cmd/xk6" = "latest"

[settings]
env_file = ".env"
